import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Match,idle} from '../src/game/simulation';
import {ReactionDirector} from '../src/game/reactions';
function setup(){const m=new Match();m.state='PLAYING';m.restartPending=false;m.lock=0;m.owner=8;for(const p of m.players){p.x=-20;p.y=p.team===0?-15:15;}Object.assign(m.players[3],{x:0,y:0,facingX:1,facingY:0});Object.assign(m.players[8],{x:1.5,y:0,facingX:-1,facingY:0});m.ball.x=.85;m.ball.y=0;return m;}
test('ball-first slide pokes a loose ball and retains committed recovery',()=>{const m=setup(),p=m.players[3];m.tackle(p,true);m.advanceActions(.17);assert.equal(m.owner,null);assert.equal(m.fouls[0],0);assert.equal(m.tackles[0],1);assert.equal(p.action?.kind,'slide');assert.ok(p.recovery>0);assert.ok(m.ball.vx>0);m.tackle(p,true);assert.equal(p.action?.elapsed,.17);});
test('a missed slide travels in its original direction and cannot turn or steal instantly',()=>{const m=setup();m.owner=null;m.players[8].y=12;m.ball.x=12;m.tackle(m.players[3],true);for(let i=0;i<20;i++)m.step(1/60,{...idle(),y:1,tackle:true});assert.equal(m.players[3].facingX,1);assert.equal(m.players[3].facingY,0);assert.equal(m.players[3].action?.kind,'slide');assert.equal(m.tackles[0],0);assert.ok(m.players[3].x>1);});
test('late rear contact is whistled once and gives the victim a legal free kick',()=>{const m=setup();Object.assign(m.players[8],{x:.7,facingX:1});m.ball.x=1.5;m.tackle(m.players[3],true);m.advanceActions(.17);assert.equal(m.state,'FOUL');assert.equal(m.fouls[0],1);const elapsed=m.elapsed;for(let i=0;i<90;i++)m.step(1/60,idle());assert.equal(m.state,'FREE_KICK');assert.equal(m.elapsed,elapsed);assert.equal(m.owner,8);assert.equal(m.setPiece?.team,1);assert.equal(m.fouls[0],1);for(const p of m.players.filter(p=>p.team===0&&!p.keeper))assert.ok(Math.hypot(p.x-m.ball.x,p.y-m.ball.y)>=4.9);});
test('foul in the defending area becomes a penalty and resets safely',()=>{const m=setup();Object.assign(m.players[3],{x:-25});Object.assign(m.players[8],{x:-25.7,y:2});m.awardFoul(m.players[3],m.players[8]);m.step(1.4,idle());assert.equal(m.state,'FREE_KICK');assert.equal(m.setPiece?.penalty,true);assert.equal(m.ball.x,-22);assert.equal(m.ball.y,0);assert.ok(m.players.every(p=>Math.abs(p.x)<=29.5&&Math.abs(p.y)<=17.5));});
test('human free kick waits for input; pass releases it once, pause freezes it',()=>{const m=setup();m.awardFoul(m.players[8],m.players[3]);m.step(1.4,idle());m.pause();m.step(10,{...idle(),shoot:true});assert.equal(m.state,'PAUSED');assert.equal(m.shots[0],0);m.pause();m.step(3,idle());assert.equal(m.state,'FREE_KICK');m.step(1/60,{...idle(),pass:true});for(let i=0;i<60&&m.state==='FREE_KICK';i++)m.step(1/60,idle());assert.equal(m.state,'PLAYING');assert.equal(m.passes[0],1);assert.equal(m.setPiece,null);});
test('sharp turns are rate limited and slow the player before reversing',()=>{const m=setup();m.owner=null;m.ball.x=25;const p=m.players[3];p.vx=7;const before=Math.atan2(p.facingY,p.facingX);m.step(1/60,{...idle(),x:-1});const after=Math.atan2(p.facingY,p.facingX);assert.ok(Math.abs(after-before)<=7/60+.0001);assert.ok(p.vx>0&&p.vx<7);});
test('turning to strike is preparation, never an instantaneous half-turn',()=>{const m=setup();m.owner=3;m.players[8].y=12;const p=m.players[3];p.facingX=-1;m.shoot(p);assert.equal(p.facingX,-1);m.step(1/60,idle());assert.equal(m.shots[0],0);assert.ok(p.action!.turnRemaining!>0);for(let i=0;i<60&&m.shots[0]===0;i++)m.step(1/60,idle());assert.equal(m.shots[0],1);});
test('near misses are emitted once per shot and late lead is not called a winner early',()=>{const m=setup();m.owner=3;m.players[3].x=25;m.ball.x=25;m.kick(m.players[3],31,3.6,25);m.advanceActions(1);m.ball.x=29.99;m.ball.y=3.6;m.ball.vx=20;m.step(1/60,idle());assert.equal(m.moments.filter(e=>e.kind==='near-goal').length,1);m.step(1/60,idle());assert.equal(m.moments.filter(e=>e.kind==='near-goal').length,1);
 m.elapsed=170;m.owner=null;m.ball.x=29.99;m.ball.y=0;m.ball.vx=20;m.step(1/60,idle());assert.ok(m.moments.some(e=>e.kind==='late-lead'));assert.ok(!m.moments.some(e=>e.kind==='late-winner'));});
test('reaction selection varies without immediate repetition and suppresses chatter spam',()=>{const d=new ReactionDirector(()=>.1);const a=d.choose('goal',3),b=d.choose('goal',3);assert.notEqual(a,b);assert.ok(d.accept({id:1,kind:'close-match',time:140,team:-1,intensity:1}));assert.ok(!d.accept({id:2,kind:'close-match',time:141,team:-1,intensity:1}));assert.ok(d.accept({id:3,kind:'goal',time:141,team:0,intensity:1}));});
test('practice has no match clock or stamina drain and keeps defenders off the press',()=>{const m=new Match();m.training=true;m.resetDrill('through');const defenders=m.players.filter(p=>p.team===1&&!p.keeper).map(p=>[p.x,p.y]);for(let i=0;i<120;i++)m.step(1/60,{...idle(),x:1,sprint:true});assert.equal(m.elapsed,0);assert.equal(m.players[3].stamina,1);assert.deepEqual(m.players.filter(p=>p.team===1&&!p.keeper).map(p=>[p.x,p.y]),defenders);assert.equal(m.fouls[0]+m.fouls[1],0);});
test('sprinting is faster than running on identical open ground',()=>{const distances=[];for(const sprint of [false,true]){const m=new Match();m.training=true;m.resetDrill();m.owner=null;m.ball.x=-20;for(let i=0;i<90;i++)m.step(1/60,{...idle(),x:1,sprint});distances.push(m.players[3].x);}assert.ok(distances[1]>distances[0]*1.3);});
test('through pass reads fresh aiming input even before the body has completed its turn',()=>{const m=setup();m.owner=3;m.players[3].facingX=-1;Object.assign(m.players[4],{x:10,y:-4});assert.ok(m.pass(m.players[3],true,false,{x:1,y:-.4}));assert.equal(m.players[3].pendingKick?.receiver,4);assert.equal(m.players[3].pendingKick?.through,true);});
