import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('artifacts/locomotion',{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{const context=await browser.newContext({viewport:{width:1280,height:800},recordVideo:{dir:'artifacts/locomotion/video',size:{width:1280,height:800}}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.waitForFunction(()=>!document.querySelector('#app').inert);
const metrics=await page.evaluate(async()=>{
 const {createCharacter,animateCharacter}=await import('/src/game/character.ts');const {Vector3}=await import('/node_modules/three/build/three.module.js');const rig=createCharacter('#ddc633',2);let maxLean=0,maxRoll=0,maxDrift=0,contacts=0,repeatError=0,stride=0,time=0;
 const motion={receive:0,recovery:0,vx:0,vy:5,facingX:0,facingY:1};
 animateCharacter(rig,1,5,0,false,null,.3,motion);const q=rig.bones.spine.quaternion.clone();for(let n=0;n<1200;n++)animateCharacter(rig,1,5,0,false,null,.3,motion);repeatError=q.angleTo(rig.bones.spine.quaternion);
 for(const speed of [0,2,5,8,5,2,0]){let previous=[null,null];for(let n=0;n<180;n++){time+=1/60;stride=(stride+speed/60/(1.1+Math.min(1,speed/8)*1.3))%1;const heading=speed?Math.sin(time*.6)*.7:0;rig.root.rotation.y=heading;rig.root.position.x+=Math.sin(heading)*speed/60;rig.root.position.z+=Math.cos(heading)*speed/60;motion.vx=Math.sin(heading)*speed;motion.vy=Math.cos(heading)*speed;motion.facingX=Math.sin(heading);motion.facingY=Math.cos(heading);animateCharacter(rig,time,speed,0,false,null,stride,motion);rig.root.updateMatrixWorld(true);maxLean=Math.max(maxLean,Math.abs(rig.bones.spine.rotation.x));maxRoll=Math.max(maxRoll,Math.abs(rig.bones.spine.rotation.z));for(let i=0;i<2;i++){const foot=rig.bones[i?'footR':'footL'].getWorldPosition(new Vector3()),plant=rig.footPlants.stance[i];if(plant&&previous[i]){maxDrift=Math.max(maxDrift,foot.distanceTo(previous[i]));contacts++;}previous[i]=plant?foot:null;}}}
 return {repeatError,maxLean,maxRoll,maxDrift,contacts};});
assert.ok(metrics.repeatError<1e-6,JSON.stringify(metrics));assert.ok(metrics.maxLean<.22,JSON.stringify(metrics));assert.ok(metrics.maxRoll<.24);assert.ok(metrics.contacts>100);assert.ok(metrics.maxDrift<.055,JSON.stringify(metrics));
await page.locator('#home-training').click();await page.waitForURL('**/#/match');await page.locator('#zoom-in').click();await page.locator('#zoom-in').click();
for(const [key,sprint] of [['ArrowRight',false],['ArrowUp',false],['ArrowLeft',true],['ArrowRight',true],['ArrowDown',false]]){await page.keyboard.down(key);if(sprint)await page.keyboard.down('Shift');await page.waitForTimeout(1700);await page.screenshot({path:`artifacts/locomotion/${key}-${sprint}.png`});await page.keyboard.up(key);await page.keyboard.up('Shift');await page.waitForTimeout(350);}
await page.locator('#pause').click();assert.deepEqual(errors,[]);await writeFile('artifacts/locomotion/metrics.json',JSON.stringify(metrics,null,2));console.log(metrics);await context.close();}finally{await browser.close();}
