import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
try{
 const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:5173/#/setup');await p.waitForFunction(()=>!document.querySelector('#app').inert);
 // Capture the real running simulation through its public method in the test only.
 await p.evaluate(async()=>{const url=performance.getEntriesByType('resource').filter(r=>r.name.includes('/src/game/simulation.ts')).at(-1).name;const {Match}=await import(url);const step=Match.prototype.step;Match.prototype.step=function(dt,input){window.liveMatch=this;return step.call(this,dt,input);};});
 await p.locator('#conditions').selectOption('night');await p.locator('#play').click();await p.waitForURL('**/#/match');await p.waitForTimeout(1700);await p.keyboard.press('Space');await p.waitForTimeout(1800);
 await p.evaluate(()=>{const m=window.liveMatch;m.restartPending=false;m.state='PLAYING';m.owner=3;m.active=3;Object.assign(m.players[3],{x:26,y:0,vx:0,vy:0,facingX:1,facingY:0,action:null,pendingKick:null,cooldown:0});Object.assign(m.players[5],{x:28,y:12});m.ball.x=26.64;m.ball.y=0;m.ball.z=0;m.ball.vx=0;m.ball.vy=0;});
 await p.keyboard.press('KeyJ');await p.waitForFunction(()=>window.liveMatch.state==='GOAL');await p.screenshot({path:'artifacts/matchday/goal.png'});await p.waitForFunction(()=>document.querySelector('#replay-banner').hidden===false);const elapsed=await p.evaluate(()=>window.liveMatch.elapsed);await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>window.liveMatch.elapsed),elapsed);await p.screenshot({path:'artifacts/matchday/night-replay.png'});
 await p.locator('#pause').click();const progress=await p.locator('#replay-progress').getAttribute('value');await p.waitForTimeout(400);assert.equal(await p.locator('#replay-progress').getAttribute('value'),progress);await p.locator('#resume').click();await p.locator('#skip-replay').click();await p.waitForFunction(()=>window.liveMatch.state==='KICKOFF');assert.equal(await p.evaluate(()=>window.liveMatch.owner),8);assert.equal(await p.evaluate(()=>window.liveMatch.score[0]),1);
 await p.waitForFunction(()=>!window.liveMatch.restartPending);await p.evaluate(()=>{window.liveMatch.elapsed=window.liveMatch.duration-.01;});await p.waitForURL('**/#/results');await p.screenshot({path:'artifacts/matchday/results.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'artifacts/matchday/phone-results.png'});await p.setViewportSize({width:1440,height:900});assert.equal(await p.locator('#result-rematch').isVisible(),true);await p.locator('#result-rematch').click();await p.waitForURL('**/#/match');await p.waitForFunction(()=>document.querySelector('#score').textContent==='0 : 0');assert.equal(await p.locator('#score').innerText(),'0 : 0');assert.deepEqual(errors,[]);console.log('Real match goal -> replay -> pause/resume -> skip -> conceding kick-off -> results -> rematch passed.');
}finally{await b.close();}
